### ISSUE TITLE
Empty Search results in full content of the application. 

### ISSUE THREAD

**Issue by balireddypraveen** [hashedin/charcha#55]
### **Type**
Bug

### **Description**
Empty Search results in the full content of the application. Maybe we can restrict this behavior.

### **Screenshots**
![screenshot_1](https://user-images.githubusercontent.com/61535337/92988259-796c8800-f4e7-11ea-8d17-b6a1bb04d5a6.png)

### **Steps to reproduce**
Login into charcha.
Click on _Search_

**Comment by mrinalraj** [comment]
Adding extra space left or right also effects the search results.

**Comment by mrinalraj** [comment]
@sripathikrishnan adding a pull request for the fix #56
